### ISSUE TITLE
yd-button自定义颜色没有点击状态

### ISSUE THREAD

**Issue by zhangenming** [ydcss/vue-ydui#15]
<yd-button size="large" bgcolor="#000" color="#FFF">Custom Color</yd-button>
是否应该提供点击状态下的bgcolor与color 
或者有其他方法实现
谢谢

**Comment by ydcss** [comment]
你好，目前没想到有什么好办法。你有什么解决方案吗？

**Comment by ydcss** [comment]
你好，点击状态下的颜色是通过伪类:active指定，props无法直接实现。但可通过自定义样式的方式实现：
`<yd-button bgcolor="#000" color="#FFF" class="custom-button">Custom Color</yd-button>
<style>
    .custom-button:active {
        background-color: #f00!important;
    }
</style>`

如果发现其他的好办法，请一定告诉我。谢谢

**Comment by lh4111** [comment]
@ydcss 试试
```css
button{
  background-color: #3395fc;
  border:none;
  padding:8px 16px;
  border-radius:2px;
  color:#fff;
  outline:none;
  cursor:pointer;
  
  position:relative;
}

button:active::after{
  content:'';
  display:block;
  position:absolute;
  left:0;
  top:0;
  height:100%;
  width:100%;
  background-color: rgba(255,255,255,.2);
}
```

http://jsbin.com/dizejaj/edit?html,css,output
