### ISSUE TITLE
请问如何引入新的icon

### ISSUE THREAD

**Issue by SCzfdf** [ydcss/vue-ydui#523]
如何引入新的icon文件(svg)

我想用新的图标文件(svg)来扩展原有的ydui图标库

而官方文档说的引入是引入ttf文件
一来在网上找不到svg转换ttf的
二来想知道是ydui是如何引入ttf文件的

在ydui.base.css文件中找到了引入icon的代码
可是src一大串是如何转化的?

**Comment by ydcss** [comment]
你好。
1、ttf和svg引入方式一样的。覆盖之前的样式即可。
```css
/* 各种格式对应各种版本浏览器 */
@font-face {
  font-family: 'iconfont';  /* project id 228144 */
  src: url('//at.alicdn.com/t/font_f7is8gs8wug6tj4i.eot');
  src: url('//at.alicdn.com/t/font_f7is8gs8wug6tj4i.eot?#iefix') format('embedded-opentype'),
  url('//at.alicdn.com/t/font_f7is8gs8wug6tj4i.woff') format('woff'),
  url('//at.alicdn.com/t/font_f7is8gs8wug6tj4i.ttf') format('truetype'),
  url('//at.alicdn.com/t/font_f7is8gs8wug6tj4i.svg#iconfont') format('svg');
}
```
2、我是将ttf转为base64了。
