### ISSUE TITLE
yd-popup组件在IOS或者微信浏览器中，点击弹框会回到页面的最顶部

### ISSUE THREAD

**Issue by lfb** [ydcss/vue-ydui#759]
## 问题
 yd-popup组件在IOS或者微信浏览器中，当浏览到页面的中间或者底部，点击触发弹框，页面会马上回到页面的最顶部，才出现 yd-popup页面，希望作者能抽空修复，谢谢

## 组件链接
[http://vue.ydui.org/docs/#/popup](http://vue.ydui.org/docs/#/popup)

## 问题重现图片：

<img width="329" alt="WX20190430-102454@2x" src="https://user-images.githubusercontent.com/26264225/56937996-3bf59d80-6b32-11e9-85cd-fbf9699e1f26.png">

**Comment by CalvinVon** [comment]
同问，正在查代码
暂时加了个样式覆盖解决
```css
body.g-fix-ios-prevent-scroll {
	position: initial !important;
}
```
